[project]
name = "art"
version = "0.1.0"
description = "3D simulator for toothpick artwork creation"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=1.26.0",
    "pillow>=10.0.0",
    "vispy>=0.14.0",
    "PyQt6>=6.5.0",
    "matplotlib>=3.8.0",
    "scipy>=1.11.0",
]
